name: 'Push to Student Version'
description: 'Run book cleaning script and push to student version repo'

runs:
  using: "composite"
  steps:

    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install the python version needed
        
    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: execute py script # run clean_book.py
      shell: bash
      run: python .github/workflows/clean_book.py

    - name: commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -a -m "cleaned books for student version" --allow-empty

    - name: push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        branch: main 
        force: true