name: 'Create Student Version'
description: 'Run book cleaning script and push to student version repo'

inputs:
  key:
    description: 'The GitHub Deploy Key for pushing to the curriculum-book-student repo'
    required: true

runs:
  using: "composite"
  steps:

    - name: checkout repo content
      uses: actions/checkout@v3 # checkout the repository content to github runner

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9' # install the python version needed
        
    - name: install python packages
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install pyyaml
        
    - name: execute py script # run clean_book.py
      shell: bash
      run: python .github/workflows/clean_book.py

    - name: commit files
      shell: bash
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git commit -a -m "cleaned books for student version" --allow-empty

    - name: push changes to student repo
      uses: cpina/github-action-push-to-another-repository@main
      env:
        SSH_DEPLOY_KEY: ${{ inputs.key }}
      with:
        source-directory: .
        destination-github-username: 'geo-smart'
        destination-repository-name: 'curriculum-book-student'
        user-email: action@github.com
        commit-message: cleaned books for student version
        target-branch: main